### PR TITLE
allow the bundle work with ezplatform

### PR DESCRIPTION
**Pull request by crevillo**
it allows the bundle work with ez platform. 
ping @andrerom @bdunogier

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by andrerom** [comment]
ping @bdunogier / @crevillo

**Comment by crevillo** [comment]
+1

**Comment by andrerom** [comment]
@crevillo You can create a new `v1.0.0-beta3` if it makes sense, would make it easier to install.

**Comment by crevillo** [comment]
done :).

**Pull request merged**
