### PR TITLE
Fix: Update with ContentUpdateStruct destroy vatRateId and isVatIncluded

### PR DESCRIPTION
**Pull request by blankse**

### CODE REVIEW

**Comment by bdunogier** [comment]
Hi, and thank you.

Thing is (but I'd need @crevillo's brains here), I think we had something else in mind for VAT handling. We talked about it a lot, and I think we concluded that VAT handling wasn't a FieldType feature, and would be provided by another API.

I'll dig around.

But what do you mean when you say it "destroys" them ?

**Comment by bdunogier** [comment]
Got something. Did you check the [dev](https://github.com/ezcommunity/EzPriceBundle/compare/dev) branch ? We have a few things here.

But more interesting is a branch from @crevillo's fork, (automatic-vat-handling)[https://github.com/crevillo/EzPriceBundle/compare/automatic-vat-handling], and in particular (this commit)[https://github.com/crevillo/EzPriceBundle/commit/e1049a2460ab5f484a5d27c3692973a423ae58ea]. It adds an AutomaticVatService, used to handle Automatic VAT (set by product category, or something, in legacy, iirc). We planned on implementing other VAT handlers using more services, but aren't done at all.

**Comment by crevillo** [comment]
Indeed we talked a lot about this. I started thinking that we should "mock" somehow how legacy works with this and in legacy you are prompted to select which vat (vat id) are applied to every product.

But to be honest, and due how laws are here in Spain, i Have had Always the need to go for "automatic" vat handling. And i think this is how the things are gonna be now with new laws. Actually when we sell something from Spain we apply Same vat to every product but Since Jan 1st it seems we will need to apply different vat per country destination.

So, as Bertrand says, we thougth vat should somehow being decoupled from the fieldtype because vat is not a price but something acting with the final price as maybe a discount or a specific shipping price for the item.

The automatic vat service branch Bertand points out was a try to simulate ezdefaultvathandler behaviour. Bad part is that default vat handler implied yo need a ezproductcategory fieldtype in your product to work but Thats another story.

But maybe @blanke is talking about editing a price with the new price and that price lost vat id on saving?

Happy new year btw :)

**Comment by blankse** [comment]
AutomaticVatService sounds good :)

My problem was when I update an product over the new ContentUpdateStruct class the price lost the vatRateId and the isVatIncluded values.

The Converter class set the isVatIncluded value as vatRateId:
https://github.com/blankse/EzPriceBundle/commit/f0141fea9c91059b5e3599f8ebdd20ece4d7dd36#diff-ce9ce2a70c74cf2cb2f8955ccf5ec424L34 and set the isVatIncluded value hard to 1

I don't see a way to get the vatRateId in the Converter and so I go the way over the Value. In legacy the vatRateId could changed for each product.

Happy new year everybody :)

**Comment by andrerom** [comment]
@blankse you can now rebase on top of master w/o the last commit, but more importantly, what's the status of this? _(could you add todo's in description if you remember any? with that we can try to help)_

**Comment by blankse** [comment]
@andrerom I rebased the PR.
I don't know the todos. I only implemented the behavior from the legacy.
I think the approach with AutomaticVatService will not be compatible with the legacy field. Or?

I see AutomaticVatService expected a VatId = -1. So this PR will not stand in the way.

**Comment by andrerom** [comment]
@crevillo ?

**Comment by crevillo** [comment]
I don't know if I follow you well... Anyway, i think that legacy indeed expected a `-1` to say that vat for that product should be calculated dinamycally. 
https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/classes/datatypes/ezprice/ezpricetype.php#L44

**Comment by blankse** [comment]
I didn't know about this functionality in legacy :flushed:
With my PR it is still possible to set the vatRateId to -1 and use the AutomaticVatService.
In the moment the isVatIncluded and the vatRateId will be set incorrectly

**Pull request closed without merging**
